name = "ass"
pages_build_output_dir = "./dist"

# [vars]
# MY_VAR = "my-variable"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

[[d1_databases]]
binding = "DB"
database_id = "a5f5170b-e538-4d78-a93e-76dae128fd3b"
database_name = "db123"
migrations_dir = "./migrations"

# [ai]
# binding = "AI"